global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'auth-service:8080'
          - 'user-service:8080'
          - 'ride-service:8080'
          - 'payment-service:8080'
          - 'api-gateway:8080'
        labels:
          application: 'ride-hailing'
