apiVersion: v1
kind: ConfigMap
metadata:
  name: ridesharing-config
  namespace: ridesharing
data:
  JWT_ACCESS_TOKEN_EXPIRATION: "900"
  JWT_REFRESH_TOKEN_EXPIRATION: "604800"
  SPRING_PROFILES_ACTIVE: "prod"
